---
title: "Missingness"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  include = TRUE, warning = FALSE, message = FALSE, echo = FALSE
)
```

```{r import data, include = FALSE}
packages_list <- c(
  "data.table", "tidyverse", "kableExtra", "MASS"
)
new_packages <- packages_list[
  !(packages_list %in% installed.packages()[, "Package"])
]
if (length(new_packages)) install.packages(new_packages)
suppressMessages(lapply(packages_list, library, character.only = TRUE))

select <- dplyr::select
rbind <- base::rbind
kable <- knitr::kable

project_folder <- file.path(
  "C:/Users/sren/Dropbox (Partners HealthCare)/BOC shared",
  "Chemo during pregnancy (Sella)"
)

# load functions needed
source(file.path(project_folder, "r", "functions.R"))

data_path <- file.path(project_folder, "data", "2020-12-9")
load(file.path(data_path, "cleaned_data.RData"))
```

Gestational age at diagnosis missing:
```{r gestational age at diagnosis missing}
redcap_data[
    is.na(gadx),
    .(chemopg, record_id)
][order(chemopg), ]

redcap_data[
    record_id %in% c(55, 85, 90),
    .(record_id, gadx, surgga, time2surg)
]

```

Breast cancer stage missing:
```{r breast cancer stage missing}
redcap_data[
    is.na(stage) | stage == 0,
    .(stage, record_id)
][order(stage), ]
```

Timing of chemotherapy missing:
```{r timing of chemotherapy missing}
redcap_data[
    anychemo == 1 & is.na(neoadjchemo),
    .(anychemo, neoadjchemo, record_id)
]
```

Gestational age at delivery missing:
```{r gestational age at delivery missing}
redcap_data[
    is.na(delga),
    .(chemopg, record_id)
][order(chemopg), ]
```

Preterm birth unknown:
```{r preterm birth unknown}
redcap_data[
    preterm_birth_reason == "" & ptd == 1,
    .(
        record_id,
        sptb,
        indptb,
        iatptb,
        ptd
    )
]
```